services:
  db:
    container_name: "postgresql"
    image: postgres:15.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - envs/db.env
    restart: on-failure
    ports:
      - "5432:5432"

  backend:
    container_name: "backend"
    build:
      context: ./backend
    volumes:
      - ./backend:/opt/app
    ports:
      - 8000:8000
    env_file:
      - envs/db.env
      - envs/backend.env
    depends_on:
      - db
    restart: on-failure


  redis:
    image: redis:7.0
    restart: on-failure
    command: redis-server
    depends_on:
      - db
    ports:
      - 6379:6379

#  proxy:
#    container_name: proxy
#    build:
#      context: ./proxy
#    restart: on-failure
#    depends_on:
#      - backend
#    networks:
#      - nginx-backend
#    ports:
#      - "80:80"

volumes:
    postgres_data:
    static_volume:
    media_volume:


networks:
  nginx-backend:
    driver: bridge
  backend-db:
    driver: bridge
