# Generated by Django 4.1.3 on 2022-11-19 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('image', models.TextField(null=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usage_per_day', models.FloatField(default=0)),
                ('updated_at', models.DateField(auto_now=True)),
                ('product_detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest.productdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductToBuy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest.productdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('expiration_date', models.DateField()),
                ('used', models.BooleanField(default=False)),
                ('to_sell', models.BooleanField(default=False)),
                ('sell_price', models.FloatField(default=0.0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest.productdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
