# Generated by Django 4.1.3 on 2022-11-19 21:23

from django.db import migrations
from ..utils import get_product_by_barcode

product_details = [{'id': '5900766000076',
                    'image': 'https://www.leclerc.rzeszow.pl//resize.php?pic=136/5900766000076_T1.jpg&x=170&y=170',
                    'name': 'Polskie Młyny Mąka Szymanowska Uniwersalna pszenna typ 480 1 kg', 'price': '3.89'},
                   {'id': '5900820000042',
                    'image': 'https://www.leclerc.rzeszow.pl//resize.php?pic=3/5900820000042_T1.jpg&x=170&y=170',
                    'name': 'Łaciate Mleko UHT 2,0 % 1 l"', 'price': '3.99'},
                   {'id': '5900552057338',
                    'image': 'https://www.leclerc.rzeszow.pl//resize.php?pic=165/5900552057338_T1.jpg&x=170&y=170',
                    'name': '4Move Professional Napój niegazowany o smaku pomarańczowym 0,75 l"', 'price': '2.07'},
                   {'id': '5900552032373',
                    'image': 'https://www.leclerc.rzeszow.pl//resize.php?pic=149/5900552032373_T1.jpg&x=170&y=170',
                    'name': 'Black Energy Mojito Gazowany napój energetyzujący 250 ml', 'price': '2.29'},
                   {'id': '5900352015040',
                    'image': 'https://www.leclerc.rzeszow.pl//resize.php?pic=177/5900352015040_T1.jpg&x=170&y=170',
                    'name': 'AKUKU! Vege Żelko-pianki lodove 75 g', 'price': '3.33'},
                   {'id': '5900334008206',
                    'image': 'https://www.leclerc.rzeszow.pl//resize.php?pic=135/5900334008206_T1.jpg&x=170&y=170',
                    'name': 'Tiger Energy Drink Classic Gazowany napój energetyzujący 250 ml', 'price': '2.28'},
                   {'id': '5902901001269',
                    'image': 'https://www.leclerc.rzeszow.pl//resize.php?pic=137/brand_18835_1.jpg&x=170&y=170',
                    'name': 'Mlekovita Śmietana z Trzebowniska 18% 380 g', 'price': '4.59'},
                   {'id': '4001954160266',
                    'image': 'https://www.leclerc.rzeszow.pl//resize.php?pic=187/4001954160266_T1.jpg&x=170&y=170',
                    'name': 'Kerrygold Tradycyjne masło irlandzkie 200 g', 'price': '8.99'},
                   {'id': '5900512990705',
                    'image': 'https://www.leclerc.rzeszow.pl//resize.php?pic=160/5900512990705_T1.jpg&x=170&y=170',
                    'name': 'Mlekovita Masło klarowane 250 g', 'price': '16.88'},
                   {'id': '5907637329670',
                    'image': 'https://www.leclerc.rzeszow.pl//resize.php?pic=170/5907637329670.jpg&x=170&y=170',
                    'name': '€.C.O.+ Migdały łuskane 300g', 'price': '13.85'},
                   {'id': '8001200045992',
                    'image': 'https://www.leclerc.rzeszow.pl//resize.php?pic=183/8001200045992_T1.jpg&x=170&y=170',
                    'name': 'Agnesi Tagliatelle Paglia & Fieno Makaron jajeczny i makaron jajeczny ze szpinakiem 250 g',
                    'price': '6.47'},
                   {'id': '3450970072311',
                    'image': 'https://www.leclerc.rzeszow.pl//resize.php?pic=170/3450970072311.jpg&x=170&y=170',
                    'name': '€.C.O.+ ORZECHY PISTACJOWE SMAZONE SOLONE 200g', 'price': '12.37'},
                   {'id': '4002039703101',
                    'image': 'https://www.leclerc.rzeszow.pl//resize.php?pic=157/4002039703101_T1.jpg&x=170&y=170',
                    'name': 'Bell Szynka Schwarzwälder 80 g', 'price': '7.99'},
                   {'id': '5900197000034',
                    'image': 'https://www.leclerc.rzeszow.pl//resize.php?pic=136/5900197000034_T1.jpg&x=170&y=170',
                    'name': 'Bakoma Jogurt naturalny gęsty 150 g', 'price': '1.29'},
                   {'id': '5902899140766',
                    'image': 'https://www.leclerc.rzeszow.pl//resize.php?pic=168/5902899140766_T1.jpg&x=170&y=170',
                    'name': 'Hochland Ser żółty Tylżycki w plastrach 135 g', 'price': '6.35'}]


def create_product_detail(apps, schema_editor):
    pass


def remove_product_details(apps, schema_editor):
    ProductDetail = apps.get_model('rest', 'ProductDetail')

    ids = [detail['id'] for detail in product_details]

    ProductDetail.objects.filter(id__in=ids).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_product_detail, remove_product_details)
    ]
