# Generated by Django 4.1.3 on 2022-11-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_rename_usage_per_day_usage_coefficient_usage_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('Basement', 'Basement'), ('Cupboard', 'Cupboard'), ('Freezer', 'Freezer'), ('Fridge', 'Fridge')], default='Fridge', max_length=10),
        ),
    ]
