# Generated by Django 4.1.3 on 2022-11-20 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest', '0003_product_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompostedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest.productdetail')),
                ('donated_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
