# Generated by Django 4.1.3 on 2022-11-20 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accepts_compost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='composter_capacity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='composter_percentage_utilization',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='owns_composter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='search_distance_in_meters',
            field=models.PositiveSmallIntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shopping_frequency',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
